#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
    - debug:
        msg: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/macos-setup-scripts')

- hosts: localhost
  connection: local
  become: no

  tasks:
    - name: MacOS specific settings
      become: yes
      script: scripts/macos-settings.sh

    - name: Clone dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: Setup Dock
      include_tasks: tasks/dock.yml

    - name: Configure file extensions
      script: scripts/file-extensions.sh

  handlers:
    - name: kill dock
      command: killall Dock

    - name: kill finder
      command: killall Finder
